# SpreedMe
#
# server consists of: spreedme-nextcloud app and spreed-webrtc server. Also STUN/TURN server for production env.
# This setup assumes you have coturn already installed.
#
# Section ref: https://github.com/strukturag/nextcloud-spreedme#installation--setup-of-a-spreed-webrtc-server
#
# The app
spreednc="$nc/apps/spreedme"
spreedncurl="https://github.com/strukturag/nextcloud-spreedme"
spreednccommit="f17a97db5ee96792d5350286db53459b00b07d14"
# The server
spreed="/opt/spreed"
spreedurl="https://github.com/strukturag/spreed-webrtc"
spreedcommit="e483679f0533bbcab063c7721df28c96fe8b86ce" # Oct 13, 2016
# Spreed-Me app install
cd $nc/apps && git clone $spreedncurl
mv $nc/apps/nextcloud-spreedme $spreednc
cd $spreednc && git reset --hard $spreednccommit
# need config file with this path to configure without using nextcloud web interface.
cd $spreednc/config/config.php.in $spreednc/config/config.php
chown -R $htuser:$htgroup spreedme

### Spreed
# Build spreed-webrtc server from source
# install dependencies
apt-get install automake autoconf golang node nodejs compass sass prefixer pybabel scsslint find gpm jshint
cd $root && git clone https://github.com/strukturag/spreed-webrtc
mv spreed-webrtc $spreed
cd $spreed && git reset --hard $spreedcommit
cd $spreed && ./autogen.sh
cd $spreed && make
chown www-data:www-data -R $spreed

### Spreed
#
# Post-install configuration

# Configuration 1 - $spreednc/config//config.php
#
# 1. Set const SPREED_WEBRTC_ORIGIN = 'cloud.example.com';
# 2. generate "const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'key';" with key=`xxd -ps -l 32 -c 32 /dev/random`

# Configuration 2 - nginx
#
# for nginx configuration see this ref: https://github.com/strukturag/nextcloud-spreedme/blob/master/doc/example-config-nginx.md#how-to-run-spreed-webrtc-with-nginx-in-subpath
# and see nginx.conf 

# Configuration 3 - $spreed/server.conf
#
# 1. Go to admin page additional settings and press both generate signing key and generate shared secret and finally generate configuration.
# 2. Copy and save in e.g. libreoffice writer.
# 3. Spreed reads server.conf from its rootdir=$spreed/server.conf, so the generated configuration needs to be placed in /opt/spreed/server.conf#

# 
# server.conf needs to be aligned with sharedsecret_secret in $spreedme/config.php
#
# Copy shared secret info from server.conf to $spreedme/config.php
# It's the following line in $spreedme/config.php that needs replaced with sharedsecret_secret from server.conf:
# const SPREED_WEBRTC_SHAREDSECRET = 'bb04fb058e2d7fd19c5bdaa129e7883195f73a9c49414a7eXXXXXXXXXXXXXXXX';
#
# Allowing temporary password logins requires a signing key to be set for "const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY" in $spreedme/config.php
#sigkey=`xxd -ps -l 32 -c 32 /dev/random`
# After these changes you need to restart spreed-webrtc-server.
# you can start the server with sudo -u www-data ./spreed-webrtc-server -l /opt/spreed/spreed.log and access it with nextcloud app.
#
# 
cd $spreedme/extra/static/config
cp OwnCloudConfig.js.in OwnCloudConfig.js

# Configuration 4 - configure mozilla browser
#
# reference: https://mozilla.github.io/webrtc-landing/
#media.getusermedia.screensharing.allowed_domains; append mydomain.com and cloud subdomain.
#media.getusermedia.audiocapture.enabled;true
#media.getusermedia.agc_enabled;true
#media.peerconnection.enabled;true
# Verify settings for
#media.peerconnection.turn.disable;false
#media.peerconnection.simulcast;true

#
# Configure 3 - /etc/spreed/server.conf
#
# Set turnURIS in /etc/spreed/ and also "root=/usr/share/spreed-webrtc-server/www" or similar if using Ubuntu, see ref.
# (generated by openssl rand -hex 32)
# cat eot the four lines below.
#;# Using TURN instead of STUN
#;# secret manually generated by openssl rand -hex 32 and is same as /etc/turnserver.conf
#turnSecret=8f3a78fade3a3dc0dcf58074708e3e86f8a92bcdd6e1214f0c795602c0523c43
#turnURIs = turn:cloud.example.com:8443?transport=udp turn:cloud.example.com:8443?transport=tcp



# Post config.
# "As of Firefox >= 36 you must append the domain being used to the allowed domains to access your screen. You do this by navigating to about:config, search for 'media.getusermedia.screensharing.allowed_domains', and append the domain to the list of strings. You can edit the field simply by double clicking on it. Ensure that you follow the syntax rules of the field."

# The
#wget https://github.com/strukturag/spreed-webrtc
#mv 
#autogen.sh
#./configure
#make




